### ISSUE TITLE
ERR_EMPTY_RESPONSE on port 5001

### ISSUE THREAD

**Issue by ntwong0** [kammce/SJSU-Dev#31]
After installing Cisco AnyConnect VPN application, process 'acwebseca' hogs up port 5001 and the user will not be able to use that port for make telemetry. Confirm with command:
`sudo lsof -i :5001`

To fix, will need to edit /SJSU-Dev/tools/Telemetry/telemetry.py (didn't find it listed in the repo) and change line 260 from 
`port = 5001`
to
`port = 5002 # or any other number that isn't currently occupied`

![screen shot 2018-02-14 at 6 27 18 pm](https://user-images.githubusercontent.com/10604448/36238134-69db7fe4-11b5-11e8-8209-e9d987a86b47.png)

**Comment by kammce** [comment]
So actually this isn't an issue for SJSU-Dev, but an issue with Telemetry. There is a PR for this change in the works at the moment, so that you can choose which port you would like to use.
